version: '3'
services:
  app:
    build: ./client/.
    volumes:
      - ./client/:/app
      - node_volume:/app/node_modules
    ports:
      - "3000:3000"
    command: yarn run dev
    environment:
      NODE_ENV: "development"
      API_URL: "http://api:5432"
  api:
    build: ./server/.
    volumes:
      - ./server/:/app
    ports:
      - "5432:5432"
    command: bash -c "pipenv install && pipenv run dev"
    environment:
      PY_ENV: "local"
      PIPENV_VERBOSITY: 1
    links:
      - db
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
      TZ: "Asia/Tokyo"

volumes:
  db_volume:
  node_volume:
